# Website settings
url: "https://www.zhurinvlad.com"

# Internal nav
nav:
  resume: "/resume"
  main:
    writing: "/writing"
    # resume: "/resume"
    # speaking: "/speaking"
    # projects: "/projects"
    # links: "/links"
    # photos: "/photos"
  writing:
    all: "/writing"
    popular: "/writing/popular"
    tags: "/writing/tags"
    rss: "/feed.xml"

# Bio settings
name: "Vladislav Zhurin"
description: "The home page of Vladislav Zhurin."
thumbnail_path: "zhurinvlad-medium.jpg"
repo_url: "https://github.com/zhurinvlad/zhurinvlad.github.io"
jsfiddle_url: "https://jsfiddle.net/user/zhurinvlad/fiddles/"
# URLs
contact_urls:
  # twitter:
  #   url: 
  #   label: "Twitter"
  #   icon: "twitter-square"
  #   username: 
  # linkedin:
  #   url: "https://www.linkedin.com/in/"
  #   label: "LinkedIn"
  #   icon: "linkedin-square"
  # facebook:
  #   url: "https://www.facebook.com/"
  #   label: "Facebook"
  #   icon: "facebook-square"
  # google:
  #   url: "https://plus.google.com/"
  #   label: "Google+"
  #   icon: "google-plus-square"
  # slideshare:
  #   url: "https://www.slideshare.net/"
  #   label: "SlideShare"
  #   icon: "slideshare"
  github:
    url: "https://github.com/zhurinvlad/"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:zhurinvlad@gmail.com"
    label: "Email"
    value: "zhurinvlad@gmail.com"
    icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'Europe/Moscow'
repository: zhurinvlad/zhurinvlad.github.io

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
